version: 2
jobs:
  build:
    working_directory: ~/singnet/snet-dapp
    environment:
      TRIGGER_BUILD_BRANCH: master
    steps:
      - run:
          name: Run install script
          command: npm install
      - run:
          name: Run build script
          command: npm run build
      - run:
          name: Run publish
          command: npm publish
      - run:
          name: Trigger platform-pipeline build
          command: |
            if [ "$CIRCLE_BRANCH" == "$TRIGGER_BUILD_BRANCH" ]
            then
              curl -u ${CIRCLECI_PLATFORM_PIPELINE_TOKEN}: \
                -d build_parameters[CIRCLE_JOB]=build \
                -d build_parameters[PARENT_PROJECT_REPONAME]="$CIRCLE_PROJECT_REPONAME" \
                -d build_parameters[PARENT_BRANCH]="$CIRCLE_BRANCH" \
                -d build_parameters[PARENT_BUILD_URL]="$CIRCLE_BUILD_URL" \
                https://circleci.com/api/v1.1/project/github/singnet/platform-pipeline/tree/${TRIGGER_BUILD_BRANCH}
            fi
